
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START"
export const PURCHASE_BURGER_ORDER_SUCCESS = "PURCHASE_BURGER_SUCCESS"
export const PURCHASE_BURGER_ORDER_FAIL = "PURCHASE_BURGER_ORDER_FAIL"